// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/admin/Auth.proto

package adminconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	admin "server/api/v1/admin"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthControllerName is the fully-qualified name of the AuthController service.
	AuthControllerName = "server.admin.AuthController"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthControllerSignOutProcedure is the fully-qualified name of the AuthController's SignOut RPC.
	AuthControllerSignOutProcedure = "/server.admin.AuthController/SignOut"
	// AuthControllerRefreshProcedure is the fully-qualified name of the AuthController's Refresh RPC.
	AuthControllerRefreshProcedure = "/server.admin.AuthController/Refresh"
	// AuthControllerUpdatePasswordProcedure is the fully-qualified name of the AuthController's
	// UpdatePassword RPC.
	AuthControllerUpdatePasswordProcedure = "/server.admin.AuthController/UpdatePassword"
	// AuthControllerUpdateEmailProcedure is the fully-qualified name of the AuthController's
	// UpdateEmail RPC.
	AuthControllerUpdateEmailProcedure = "/server.admin.AuthController/UpdateEmail"
	// AuthControllerRegisterProcedure is the fully-qualified name of the AuthController's Register RPC.
	AuthControllerRegisterProcedure = "/server.admin.AuthController/Register"
	// AuthControllerResendInviteMailProcedure is the fully-qualified name of the AuthController's
	// ResendInviteMail RPC.
	AuthControllerResendInviteMailProcedure = "/server.admin.AuthController/ResendInviteMail"
)

// AuthControllerClient is a client for the server.admin.AuthController service.
type AuthControllerClient interface {
	// トークン必要
	SignOut(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	Refresh(context.Context, *connect_go.Request[admin.AdminRefreshTokenRequest]) (*connect_go.Response[admin.AdminAuthTokenResponse], error)
	UpdatePassword(context.Context, *connect_go.Request[admin.UpdatePasswordRequest]) (*connect_go.Response[emptypb.Empty], error)
	UpdateEmail(context.Context, *connect_go.Request[admin.UpdateEmailRequest]) (*connect_go.Response[emptypb.Empty], error)
	Register(context.Context, *connect_go.Request[admin.AdminRegisterRequest]) (*connect_go.Response[admin.AdminRegisterResponse], error)
	ResendInviteMail(context.Context, *connect_go.Request[admin.ResendInviteRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewAuthControllerClient constructs a client for the server.admin.AuthController service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthControllerClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthControllerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authControllerClient{
		signOut: connect_go.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+AuthControllerSignOutProcedure,
			opts...,
		),
		refresh: connect_go.NewClient[admin.AdminRefreshTokenRequest, admin.AdminAuthTokenResponse](
			httpClient,
			baseURL+AuthControllerRefreshProcedure,
			opts...,
		),
		updatePassword: connect_go.NewClient[admin.UpdatePasswordRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthControllerUpdatePasswordProcedure,
			opts...,
		),
		updateEmail: connect_go.NewClient[admin.UpdateEmailRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthControllerUpdateEmailProcedure,
			opts...,
		),
		register: connect_go.NewClient[admin.AdminRegisterRequest, admin.AdminRegisterResponse](
			httpClient,
			baseURL+AuthControllerRegisterProcedure,
			opts...,
		),
		resendInviteMail: connect_go.NewClient[admin.ResendInviteRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthControllerResendInviteMailProcedure,
			opts...,
		),
	}
}

// authControllerClient implements AuthControllerClient.
type authControllerClient struct {
	signOut          *connect_go.Client[emptypb.Empty, emptypb.Empty]
	refresh          *connect_go.Client[admin.AdminRefreshTokenRequest, admin.AdminAuthTokenResponse]
	updatePassword   *connect_go.Client[admin.UpdatePasswordRequest, emptypb.Empty]
	updateEmail      *connect_go.Client[admin.UpdateEmailRequest, emptypb.Empty]
	register         *connect_go.Client[admin.AdminRegisterRequest, admin.AdminRegisterResponse]
	resendInviteMail *connect_go.Client[admin.ResendInviteRequest, emptypb.Empty]
}

// SignOut calls server.admin.AuthController.SignOut.
func (c *authControllerClient) SignOut(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return c.signOut.CallUnary(ctx, req)
}

// Refresh calls server.admin.AuthController.Refresh.
func (c *authControllerClient) Refresh(ctx context.Context, req *connect_go.Request[admin.AdminRefreshTokenRequest]) (*connect_go.Response[admin.AdminAuthTokenResponse], error) {
	return c.refresh.CallUnary(ctx, req)
}

// UpdatePassword calls server.admin.AuthController.UpdatePassword.
func (c *authControllerClient) UpdatePassword(ctx context.Context, req *connect_go.Request[admin.UpdatePasswordRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.updatePassword.CallUnary(ctx, req)
}

// UpdateEmail calls server.admin.AuthController.UpdateEmail.
func (c *authControllerClient) UpdateEmail(ctx context.Context, req *connect_go.Request[admin.UpdateEmailRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.updateEmail.CallUnary(ctx, req)
}

// Register calls server.admin.AuthController.Register.
func (c *authControllerClient) Register(ctx context.Context, req *connect_go.Request[admin.AdminRegisterRequest]) (*connect_go.Response[admin.AdminRegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// ResendInviteMail calls server.admin.AuthController.ResendInviteMail.
func (c *authControllerClient) ResendInviteMail(ctx context.Context, req *connect_go.Request[admin.ResendInviteRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.resendInviteMail.CallUnary(ctx, req)
}

// AuthControllerHandler is an implementation of the server.admin.AuthController service.
type AuthControllerHandler interface {
	// トークン必要
	SignOut(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	Refresh(context.Context, *connect_go.Request[admin.AdminRefreshTokenRequest]) (*connect_go.Response[admin.AdminAuthTokenResponse], error)
	UpdatePassword(context.Context, *connect_go.Request[admin.UpdatePasswordRequest]) (*connect_go.Response[emptypb.Empty], error)
	UpdateEmail(context.Context, *connect_go.Request[admin.UpdateEmailRequest]) (*connect_go.Response[emptypb.Empty], error)
	Register(context.Context, *connect_go.Request[admin.AdminRegisterRequest]) (*connect_go.Response[admin.AdminRegisterResponse], error)
	ResendInviteMail(context.Context, *connect_go.Request[admin.ResendInviteRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewAuthControllerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthControllerHandler(svc AuthControllerHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	authControllerSignOutHandler := connect_go.NewUnaryHandler(
		AuthControllerSignOutProcedure,
		svc.SignOut,
		opts...,
	)
	authControllerRefreshHandler := connect_go.NewUnaryHandler(
		AuthControllerRefreshProcedure,
		svc.Refresh,
		opts...,
	)
	authControllerUpdatePasswordHandler := connect_go.NewUnaryHandler(
		AuthControllerUpdatePasswordProcedure,
		svc.UpdatePassword,
		opts...,
	)
	authControllerUpdateEmailHandler := connect_go.NewUnaryHandler(
		AuthControllerUpdateEmailProcedure,
		svc.UpdateEmail,
		opts...,
	)
	authControllerRegisterHandler := connect_go.NewUnaryHandler(
		AuthControllerRegisterProcedure,
		svc.Register,
		opts...,
	)
	authControllerResendInviteMailHandler := connect_go.NewUnaryHandler(
		AuthControllerResendInviteMailProcedure,
		svc.ResendInviteMail,
		opts...,
	)
	return "/server.admin.AuthController/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthControllerSignOutProcedure:
			authControllerSignOutHandler.ServeHTTP(w, r)
		case AuthControllerRefreshProcedure:
			authControllerRefreshHandler.ServeHTTP(w, r)
		case AuthControllerUpdatePasswordProcedure:
			authControllerUpdatePasswordHandler.ServeHTTP(w, r)
		case AuthControllerUpdateEmailProcedure:
			authControllerUpdateEmailHandler.ServeHTTP(w, r)
		case AuthControllerRegisterProcedure:
			authControllerRegisterHandler.ServeHTTP(w, r)
		case AuthControllerResendInviteMailProcedure:
			authControllerResendInviteMailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthControllerHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthControllerHandler struct{}

func (UnimplementedAuthControllerHandler) SignOut(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.SignOut is not implemented"))
}

func (UnimplementedAuthControllerHandler) Refresh(context.Context, *connect_go.Request[admin.AdminRefreshTokenRequest]) (*connect_go.Response[admin.AdminAuthTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.Refresh is not implemented"))
}

func (UnimplementedAuthControllerHandler) UpdatePassword(context.Context, *connect_go.Request[admin.UpdatePasswordRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.UpdatePassword is not implemented"))
}

func (UnimplementedAuthControllerHandler) UpdateEmail(context.Context, *connect_go.Request[admin.UpdateEmailRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.UpdateEmail is not implemented"))
}

func (UnimplementedAuthControllerHandler) Register(context.Context, *connect_go.Request[admin.AdminRegisterRequest]) (*connect_go.Response[admin.AdminRegisterResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.Register is not implemented"))
}

func (UnimplementedAuthControllerHandler) ResendInviteMail(context.Context, *connect_go.Request[admin.ResendInviteRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.admin.AuthController.ResendInviteMail is not implemented"))
}
