// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/admin/MailMagazine.proto

package adminconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	admin "server/api/v1/admin"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MailMagazineControllerName is the fully-qualified name of the MailMagazineController service.
	MailMagazineControllerName = "server.admin.MailMagazineController"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MailMagazineControllerGetListProcedure is the fully-qualified name of the
	// MailMagazineController's GetList RPC.
	MailMagazineControllerGetListProcedure = "/server.admin.MailMagazineController/GetList"
	// MailMagazineControllerGetByIDProcedure is the fully-qualified name of the
	// MailMagazineController's GetByID RPC.
	MailMagazineControllerGetByIDProcedure = "/server.admin.MailMagazineController/GetByID"
	// MailMagazineControllerGetUserLogListProcedure is the fully-qualified name of the
	// MailMagazineController's GetUserLogList RPC.
	MailMagazineControllerGetUserLogListProcedure = "/server.admin.MailMagazineController/GetUserLogList"
	// MailMagazineControllerSaveDraftProcedure is the fully-qualified name of the
	// MailMagazineController's SaveDraft RPC.
	MailMagazineControllerSaveDraftProcedure = "/server.admin.MailMagazineController/SaveDraft"
	// MailMagazineControllerUpdateProcedure is the fully-qualified name of the MailMagazineController's
	// Update RPC.
	MailMagazineControllerUpdateProcedure = "/server.admin.MailMagazineController/Update"
	// MailMagazineControllerDeleteProcedure is the fully-qualified name of the MailMagazineController's
	// Delete RPC.
	MailMagazineControllerDeleteProcedure = "/server.admin.MailMagazineController/Delete"
	// MailMagazineControllerSendProcedure is the fully-qualified name of the MailMagazineController's
	// Send RPC.
	MailMagazineControllerSendProcedure = "/server.admin.MailMagazineController/Send"
)

// MailMagazineControllerClient is a client for the server.admin.MailMagazineController service.
type MailMagazineControllerClient interface {
	GetList(context.Context, *connect.Request[admin.GetMailMagazineListRequest]) (*connect.Response[admin.MailMagazinesResponse], error)
	GetByID(context.Context, *connect.Request[admin.MailMagazineIDRequest]) (*connect.Response[admin.MailMagazine], error)
	GetUserLogList(context.Context, *connect.Request[admin.UserLogListRequest]) (*connect.Response[admin.UserMailMagazineLogResponse], error)
	SaveDraft(context.Context, *connect.Request[admin.SaveDraftRequest]) (*connect.Response[admin.MailMagazine], error)
	Update(context.Context, *connect.Request[admin.UpdateMailMagazineRequest]) (*connect.Response[admin.MailMagazine], error)
	Delete(context.Context, *connect.Request[admin.DeleteMailMagazineRequest]) (*connect.Response[emptypb.Empty], error)
	Send(context.Context, *connect.Request[admin.SendMailMagazineRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewMailMagazineControllerClient constructs a client for the server.admin.MailMagazineController
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMailMagazineControllerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MailMagazineControllerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mailMagazineControllerMethods := admin.File_v1_admin_MailMagazine_proto.Services().ByName("MailMagazineController").Methods()
	return &mailMagazineControllerClient{
		getList: connect.NewClient[admin.GetMailMagazineListRequest, admin.MailMagazinesResponse](
			httpClient,
			baseURL+MailMagazineControllerGetListProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("GetList")),
			connect.WithClientOptions(opts...),
		),
		getByID: connect.NewClient[admin.MailMagazineIDRequest, admin.MailMagazine](
			httpClient,
			baseURL+MailMagazineControllerGetByIDProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("GetByID")),
			connect.WithClientOptions(opts...),
		),
		getUserLogList: connect.NewClient[admin.UserLogListRequest, admin.UserMailMagazineLogResponse](
			httpClient,
			baseURL+MailMagazineControllerGetUserLogListProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("GetUserLogList")),
			connect.WithClientOptions(opts...),
		),
		saveDraft: connect.NewClient[admin.SaveDraftRequest, admin.MailMagazine](
			httpClient,
			baseURL+MailMagazineControllerSaveDraftProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("SaveDraft")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[admin.UpdateMailMagazineRequest, admin.MailMagazine](
			httpClient,
			baseURL+MailMagazineControllerUpdateProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[admin.DeleteMailMagazineRequest, emptypb.Empty](
			httpClient,
			baseURL+MailMagazineControllerDeleteProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		send: connect.NewClient[admin.SendMailMagazineRequest, emptypb.Empty](
			httpClient,
			baseURL+MailMagazineControllerSendProcedure,
			connect.WithSchema(mailMagazineControllerMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mailMagazineControllerClient implements MailMagazineControllerClient.
type mailMagazineControllerClient struct {
	getList        *connect.Client[admin.GetMailMagazineListRequest, admin.MailMagazinesResponse]
	getByID        *connect.Client[admin.MailMagazineIDRequest, admin.MailMagazine]
	getUserLogList *connect.Client[admin.UserLogListRequest, admin.UserMailMagazineLogResponse]
	saveDraft      *connect.Client[admin.SaveDraftRequest, admin.MailMagazine]
	update         *connect.Client[admin.UpdateMailMagazineRequest, admin.MailMagazine]
	delete         *connect.Client[admin.DeleteMailMagazineRequest, emptypb.Empty]
	send           *connect.Client[admin.SendMailMagazineRequest, emptypb.Empty]
}

// GetList calls server.admin.MailMagazineController.GetList.
func (c *mailMagazineControllerClient) GetList(ctx context.Context, req *connect.Request[admin.GetMailMagazineListRequest]) (*connect.Response[admin.MailMagazinesResponse], error) {
	return c.getList.CallUnary(ctx, req)
}

// GetByID calls server.admin.MailMagazineController.GetByID.
func (c *mailMagazineControllerClient) GetByID(ctx context.Context, req *connect.Request[admin.MailMagazineIDRequest]) (*connect.Response[admin.MailMagazine], error) {
	return c.getByID.CallUnary(ctx, req)
}

// GetUserLogList calls server.admin.MailMagazineController.GetUserLogList.
func (c *mailMagazineControllerClient) GetUserLogList(ctx context.Context, req *connect.Request[admin.UserLogListRequest]) (*connect.Response[admin.UserMailMagazineLogResponse], error) {
	return c.getUserLogList.CallUnary(ctx, req)
}

// SaveDraft calls server.admin.MailMagazineController.SaveDraft.
func (c *mailMagazineControllerClient) SaveDraft(ctx context.Context, req *connect.Request[admin.SaveDraftRequest]) (*connect.Response[admin.MailMagazine], error) {
	return c.saveDraft.CallUnary(ctx, req)
}

// Update calls server.admin.MailMagazineController.Update.
func (c *mailMagazineControllerClient) Update(ctx context.Context, req *connect.Request[admin.UpdateMailMagazineRequest]) (*connect.Response[admin.MailMagazine], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls server.admin.MailMagazineController.Delete.
func (c *mailMagazineControllerClient) Delete(ctx context.Context, req *connect.Request[admin.DeleteMailMagazineRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// Send calls server.admin.MailMagazineController.Send.
func (c *mailMagazineControllerClient) Send(ctx context.Context, req *connect.Request[admin.SendMailMagazineRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.send.CallUnary(ctx, req)
}

// MailMagazineControllerHandler is an implementation of the server.admin.MailMagazineController
// service.
type MailMagazineControllerHandler interface {
	GetList(context.Context, *connect.Request[admin.GetMailMagazineListRequest]) (*connect.Response[admin.MailMagazinesResponse], error)
	GetByID(context.Context, *connect.Request[admin.MailMagazineIDRequest]) (*connect.Response[admin.MailMagazine], error)
	GetUserLogList(context.Context, *connect.Request[admin.UserLogListRequest]) (*connect.Response[admin.UserMailMagazineLogResponse], error)
	SaveDraft(context.Context, *connect.Request[admin.SaveDraftRequest]) (*connect.Response[admin.MailMagazine], error)
	Update(context.Context, *connect.Request[admin.UpdateMailMagazineRequest]) (*connect.Response[admin.MailMagazine], error)
	Delete(context.Context, *connect.Request[admin.DeleteMailMagazineRequest]) (*connect.Response[emptypb.Empty], error)
	Send(context.Context, *connect.Request[admin.SendMailMagazineRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewMailMagazineControllerHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMailMagazineControllerHandler(svc MailMagazineControllerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mailMagazineControllerMethods := admin.File_v1_admin_MailMagazine_proto.Services().ByName("MailMagazineController").Methods()
	mailMagazineControllerGetListHandler := connect.NewUnaryHandler(
		MailMagazineControllerGetListProcedure,
		svc.GetList,
		connect.WithSchema(mailMagazineControllerMethods.ByName("GetList")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerGetByIDHandler := connect.NewUnaryHandler(
		MailMagazineControllerGetByIDProcedure,
		svc.GetByID,
		connect.WithSchema(mailMagazineControllerMethods.ByName("GetByID")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerGetUserLogListHandler := connect.NewUnaryHandler(
		MailMagazineControllerGetUserLogListProcedure,
		svc.GetUserLogList,
		connect.WithSchema(mailMagazineControllerMethods.ByName("GetUserLogList")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerSaveDraftHandler := connect.NewUnaryHandler(
		MailMagazineControllerSaveDraftProcedure,
		svc.SaveDraft,
		connect.WithSchema(mailMagazineControllerMethods.ByName("SaveDraft")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerUpdateHandler := connect.NewUnaryHandler(
		MailMagazineControllerUpdateProcedure,
		svc.Update,
		connect.WithSchema(mailMagazineControllerMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerDeleteHandler := connect.NewUnaryHandler(
		MailMagazineControllerDeleteProcedure,
		svc.Delete,
		connect.WithSchema(mailMagazineControllerMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	mailMagazineControllerSendHandler := connect.NewUnaryHandler(
		MailMagazineControllerSendProcedure,
		svc.Send,
		connect.WithSchema(mailMagazineControllerMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	return "/server.admin.MailMagazineController/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MailMagazineControllerGetListProcedure:
			mailMagazineControllerGetListHandler.ServeHTTP(w, r)
		case MailMagazineControllerGetByIDProcedure:
			mailMagazineControllerGetByIDHandler.ServeHTTP(w, r)
		case MailMagazineControllerGetUserLogListProcedure:
			mailMagazineControllerGetUserLogListHandler.ServeHTTP(w, r)
		case MailMagazineControllerSaveDraftProcedure:
			mailMagazineControllerSaveDraftHandler.ServeHTTP(w, r)
		case MailMagazineControllerUpdateProcedure:
			mailMagazineControllerUpdateHandler.ServeHTTP(w, r)
		case MailMagazineControllerDeleteProcedure:
			mailMagazineControllerDeleteHandler.ServeHTTP(w, r)
		case MailMagazineControllerSendProcedure:
			mailMagazineControllerSendHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMailMagazineControllerHandler returns CodeUnimplemented from all methods.
type UnimplementedMailMagazineControllerHandler struct{}

func (UnimplementedMailMagazineControllerHandler) GetList(context.Context, *connect.Request[admin.GetMailMagazineListRequest]) (*connect.Response[admin.MailMagazinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.GetList is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) GetByID(context.Context, *connect.Request[admin.MailMagazineIDRequest]) (*connect.Response[admin.MailMagazine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.GetByID is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) GetUserLogList(context.Context, *connect.Request[admin.UserLogListRequest]) (*connect.Response[admin.UserMailMagazineLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.GetUserLogList is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) SaveDraft(context.Context, *connect.Request[admin.SaveDraftRequest]) (*connect.Response[admin.MailMagazine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.SaveDraft is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) Update(context.Context, *connect.Request[admin.UpdateMailMagazineRequest]) (*connect.Response[admin.MailMagazine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.Update is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) Delete(context.Context, *connect.Request[admin.DeleteMailMagazineRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.Delete is not implemented"))
}

func (UnimplementedMailMagazineControllerHandler) Send(context.Context, *connect.Request[admin.SendMailMagazineRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("server.admin.MailMagazineController.Send is not implemented"))
}
