version: '3.8'
services:
  server:
    container_name: heiwadai-server
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile
    volumes:
      - ./docker/data/server/bin:/go/bin:Z
      - ./server:/server
    ports:
      - 3000:3000
  redis:
    container_name: heiwadai-redis
    image: redis:7.0.12
    restart: unless-stopped
    ports:
      - ${REDISPORT}:${REDISPORT}
    environment:
      REDIS_ARGS: --save 5 30 --appendonly yes
    volumes:
      - ./docker/data/redis/data:/data:Z
  envoy:
    container_name: heiwadai-envoy
    image: envoyproxy/envoy:v1.20.0
    restart: unless-stopped
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml:Z
    ports:
      - 9000:9000
      - 9901:9901
    depends_on:
      - server
