version: "3.8"

services:
  server:
    container_name: heiwadai-server-dev
    image: golang:1.24-bullseye
    tty: true
    env_file: ./.env
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
    command: bash -c "go install github.com/cosmtrek/air@v1.44.0 && air"
    depends_on:
      - redis
  redis:
    container_name: heiwadai-redis
    image: redis:7.0.12
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: --save 5 30 --appendonly yes
    volumes:
      - ./docker/data/redis/data:/data:Z
