services:
  server:
    container_name: heiwadai-server.prod
    tty: true
    env_file: ./.env.prod
    environment:
      - PORT=3000
      - ENV_MODE=prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile.prod
    ports:
      - 3000:3000

