services:
  server:
    container_name: heiwadai-server
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
  redis:
    container_name: heiwadai-redis
    image: redis:7.0.12
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: --save 5 30 --appendonly yes
    volumes:
      - ./docker/data/redis/data:/data:Z
