// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/user/Reservation.proto

package userconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	user "server/api/v1/user"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ReservationControllerName is the fully-qualified name of the ReservationController service.
	ReservationControllerName = "server.user.ReservationController"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReservationControllerGetReservationProcedure is the fully-qualified name of the
	// ReservationController's GetReservation RPC.
	ReservationControllerGetReservationProcedure = "/server.user.ReservationController/GetReservation"
)

// ReservationControllerClient is a client for the server.user.ReservationController service.
type ReservationControllerClient interface {
	GetReservation(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[user.ReservationResponse], error)
}

// NewReservationControllerClient constructs a client for the server.user.ReservationController
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReservationControllerClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ReservationControllerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &reservationControllerClient{
		getReservation: connect_go.NewClient[emptypb.Empty, user.ReservationResponse](
			httpClient,
			baseURL+ReservationControllerGetReservationProcedure,
			opts...,
		),
	}
}

// reservationControllerClient implements ReservationControllerClient.
type reservationControllerClient struct {
	getReservation *connect_go.Client[emptypb.Empty, user.ReservationResponse]
}

// GetReservation calls server.user.ReservationController.GetReservation.
func (c *reservationControllerClient) GetReservation(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[user.ReservationResponse], error) {
	return c.getReservation.CallUnary(ctx, req)
}

// ReservationControllerHandler is an implementation of the server.user.ReservationController
// service.
type ReservationControllerHandler interface {
	GetReservation(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[user.ReservationResponse], error)
}

// NewReservationControllerHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReservationControllerHandler(svc ReservationControllerHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	reservationControllerGetReservationHandler := connect_go.NewUnaryHandler(
		ReservationControllerGetReservationProcedure,
		svc.GetReservation,
		opts...,
	)
	return "/server.user.ReservationController/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReservationControllerGetReservationProcedure:
			reservationControllerGetReservationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReservationControllerHandler returns CodeUnimplemented from all methods.
type UnimplementedReservationControllerHandler struct{}

func (UnimplementedReservationControllerHandler) GetReservation(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[user.ReservationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("server.user.ReservationController.GetReservation is not implemented"))
}
