FROM golang:1.23.2 as builder
RUN mkdir server
WORKDIR /server
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

# RUN apt-get update
COPY ./server .

RUN go build -o main .

# runtime image
FROM alpine:3.18
COPY --from=builder /server/main /app/main
RUN chmod +x /app/main

# copy zoneinfo.zip
COPY --from=builder /usr/local/go/lib/time/zoneinfo.zip /
ENV ZONEINFO=/zoneinfo.zip

EXPOSE 3000
CMD ["/app/main"] 