FROM golang:1.20.5-bullseye as builder
RUN mkdir server
WORKDIR /server

# RUN apt-get update
COPY ./server .

RUN CGO_ENABLED=0 go build -o main .

# runtime image
FROM alpine:3.18
COPY --from=builder /server/main /app/main
RUN chmod +x /app/main
EXPOSE 3000
CMD ["/app/main"] 