// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/admin/AnonAuth.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuthRequest) Reset() {
	*x = AdminAuthRequest{}
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuthRequest) ProtoMessage() {}

func (x *AdminAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuthRequest.ProtoReflect.Descriptor instead.
func (*AdminAuthRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_AnonAuth_proto_rawDescGZIP(), []int{0}
}

func (x *AdminAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AnonAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonAuthTokenResponse) Reset() {
	*x = AnonAuthTokenResponse{}
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonAuthTokenResponse) ProtoMessage() {}

func (x *AnonAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AnonAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_AnonAuth_proto_rawDescGZIP(), []int{1}
}

func (x *AnonAuthTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AnonAuthTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AnonAuthTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SetNewPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNewPasswordRequest) Reset() {
	*x = SetNewPasswordRequest{}
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNewPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNewPasswordRequest) ProtoMessage() {}

func (x *SetNewPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNewPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetNewPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_AnonAuth_proto_rawDescGZIP(), []int{2}
}

func (x *SetNewPasswordRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetNewPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_AnonAuth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_AnonAuth_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_v1_admin_AnonAuth_proto protoreflect.FileDescriptor

const file_v1_admin_AnonAuth_proto_rawDesc = "" +
	"\n" +
	"\x17v1/admin/AnonAuth.proto\x12\fserver.admin\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x10AdminAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"{\n" +
	"\x15AnonAuthTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1c\n" +
	"\texpiresIn\x18\x02 \x01(\x03R\texpiresIn\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\"U\n" +
	"\x15SetNewPasswordRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\",\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email2\xcd\x02\n" +
	"\x12AnonAuthController\x12B\n" +
	"\x06SignUp\x12\x1e.server.admin.AdminAuthRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x06SignIn\x12\x1e.server.admin.AdminAuthRequest\x1a#.server.admin.AnonAuthTokenResponse\"\x00\x12Q\n" +
	"\x11ResetPasswordMail\x12\".server.admin.ResetPasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x0eSetNewPassword\x12#.server.admin.SetNewPasswordRequest\x1a\x16.google.protobuf.Empty\"\x00B\x87\x01\n" +
	"\x10com.server.adminB\rAnonAuthProtoP\x01Z\x13server/api/v1/admin\xa2\x02\x03SAX\xaa\x02\fServer.Admin\xca\x02\fServer\\Admin\xe2\x02\x18Server\\Admin\\GPBMetadata\xea\x02\rServer::Adminb\x06proto3"

var (
	file_v1_admin_AnonAuth_proto_rawDescOnce sync.Once
	file_v1_admin_AnonAuth_proto_rawDescData []byte
)

func file_v1_admin_AnonAuth_proto_rawDescGZIP() []byte {
	file_v1_admin_AnonAuth_proto_rawDescOnce.Do(func() {
		file_v1_admin_AnonAuth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_AnonAuth_proto_rawDesc), len(file_v1_admin_AnonAuth_proto_rawDesc)))
	})
	return file_v1_admin_AnonAuth_proto_rawDescData
}

var file_v1_admin_AnonAuth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_admin_AnonAuth_proto_goTypes = []any{
	(*AdminAuthRequest)(nil),      // 0: server.admin.AdminAuthRequest
	(*AnonAuthTokenResponse)(nil), // 1: server.admin.AnonAuthTokenResponse
	(*SetNewPasswordRequest)(nil), // 2: server.admin.SetNewPasswordRequest
	(*ResetPasswordRequest)(nil),  // 3: server.admin.ResetPasswordRequest
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_v1_admin_AnonAuth_proto_depIdxs = []int32{
	0, // 0: server.admin.AnonAuthController.SignUp:input_type -> server.admin.AdminAuthRequest
	0, // 1: server.admin.AnonAuthController.SignIn:input_type -> server.admin.AdminAuthRequest
	3, // 2: server.admin.AnonAuthController.ResetPasswordMail:input_type -> server.admin.ResetPasswordRequest
	2, // 3: server.admin.AnonAuthController.SetNewPassword:input_type -> server.admin.SetNewPasswordRequest
	4, // 4: server.admin.AnonAuthController.SignUp:output_type -> google.protobuf.Empty
	1, // 5: server.admin.AnonAuthController.SignIn:output_type -> server.admin.AnonAuthTokenResponse
	4, // 6: server.admin.AnonAuthController.ResetPasswordMail:output_type -> google.protobuf.Empty
	4, // 7: server.admin.AnonAuthController.SetNewPassword:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_admin_AnonAuth_proto_init() }
func file_v1_admin_AnonAuth_proto_init() {
	if File_v1_admin_AnonAuth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_AnonAuth_proto_rawDesc), len(file_v1_admin_AnonAuth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_AnonAuth_proto_goTypes,
		DependencyIndexes: file_v1_admin_AnonAuth_proto_depIdxs,
		MessageInfos:      file_v1_admin_AnonAuth_proto_msgTypes,
	}.Build()
	File_v1_admin_AnonAuth_proto = out.File
	file_v1_admin_AnonAuth_proto_goTypes = nil
	file_v1_admin_AnonAuth_proto_depIdxs = nil
}
