// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/admin/Auth.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRefreshTokenRequest) Reset() {
	*x = AdminRefreshTokenRequest{}
	mi := &file_v1_admin_Auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRefreshTokenRequest) ProtoMessage() {}

func (x *AdminRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*AdminRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRefreshTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AdminRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AdminAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuthTokenResponse) Reset() {
	*x = AdminAuthTokenResponse{}
	mi := &file_v1_admin_Auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuthTokenResponse) ProtoMessage() {}

func (x *AdminAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AdminAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{1}
}

func (x *AdminAuthTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AdminAuthTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AdminAuthTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_v1_admin_Auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=Mail,proto3" json:"Mail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_v1_admin_Auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmailRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

type AdminRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mail          string                 `protobuf:"bytes,2,opt,name=Mail,proto3" json:"Mail,omitempty"`
	BelongStoreID string                 `protobuf:"bytes,4,opt,name=BelongStoreID,proto3" json:"BelongStoreID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterRequest) Reset() {
	*x = AdminRegisterRequest{}
	mi := &file_v1_admin_Auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterRequest) ProtoMessage() {}

func (x *AdminRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterRequest.ProtoReflect.Descriptor instead.
func (*AdminRegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{4}
}

func (x *AdminRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRegisterRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *AdminRegisterRequest) GetBelongStoreID() string {
	if x != nil {
		return x.BelongStoreID
	}
	return ""
}

type AdminRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterResponse) Reset() {
	*x = AdminRegisterResponse{}
	mi := &file_v1_admin_Auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterResponse) ProtoMessage() {}

func (x *AdminRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterResponse.ProtoReflect.Descriptor instead.
func (*AdminRegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{5}
}

func (x *AdminRegisterResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ResendInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=Mail,proto3" json:"Mail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendInviteRequest) Reset() {
	*x = ResendInviteRequest{}
	mi := &file_v1_admin_Auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendInviteRequest) ProtoMessage() {}

func (x *ResendInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendInviteRequest.ProtoReflect.Descriptor instead.
func (*ResendInviteRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Auth_proto_rawDescGZIP(), []int{6}
}

func (x *ResendInviteRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

var File_v1_admin_Auth_proto protoreflect.FileDescriptor

const file_v1_admin_Auth_proto_rawDesc = "" +
	"\n" +
	"\x13v1/admin/Auth.proto\x12\fserver.admin\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x18AdminRefreshTokenRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"|\n" +
	"\x16AdminAuthTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1c\n" +
	"\texpiresIn\x18\x02 \x01(\x03R\texpiresIn\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\"3\n" +
	"\x15UpdatePasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"(\n" +
	"\x12UpdateEmailRequest\x12\x12\n" +
	"\x04Mail\x18\x01 \x01(\tR\x04Mail\"d\n" +
	"\x14AdminRegisterRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Mail\x18\x02 \x01(\tR\x04Mail\x12$\n" +
	"\rBelongStoreID\x18\x04 \x01(\tR\rBelongStoreID\"'\n" +
	"\x15AdminRegisterResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\")\n" +
	"\x13ResendInviteRequest\x12\x12\n" +
	"\x04Mail\x18\x01 \x01(\tR\x04Mail2\xec\x03\n" +
	"\x0eAuthController\x12;\n" +
	"\aSignOut\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12Y\n" +
	"\aRefresh\x12&.server.admin.AdminRefreshTokenRequest\x1a$.server.admin.AdminAuthTokenResponse\"\x00\x12O\n" +
	"\x0eUpdatePassword\x12#.server.admin.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\vUpdateEmail\x12 .server.admin.UpdateEmailRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\bRegister\x12\".server.admin.AdminRegisterRequest\x1a#.server.admin.AdminRegisterResponse\"\x00\x12O\n" +
	"\x10ResendInviteMail\x12!.server.admin.ResendInviteRequest\x1a\x16.google.protobuf.Empty\"\x00B\x83\x01\n" +
	"\x10com.server.adminB\tAuthProtoP\x01Z\x13server/api/v1/admin\xa2\x02\x03SAX\xaa\x02\fServer.Admin\xca\x02\fServer\\Admin\xe2\x02\x18Server\\Admin\\GPBMetadata\xea\x02\rServer::Adminb\x06proto3"

var (
	file_v1_admin_Auth_proto_rawDescOnce sync.Once
	file_v1_admin_Auth_proto_rawDescData []byte
)

func file_v1_admin_Auth_proto_rawDescGZIP() []byte {
	file_v1_admin_Auth_proto_rawDescOnce.Do(func() {
		file_v1_admin_Auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_Auth_proto_rawDesc), len(file_v1_admin_Auth_proto_rawDesc)))
	})
	return file_v1_admin_Auth_proto_rawDescData
}

var file_v1_admin_Auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_admin_Auth_proto_goTypes = []any{
	(*AdminRefreshTokenRequest)(nil), // 0: server.admin.AdminRefreshTokenRequest
	(*AdminAuthTokenResponse)(nil),   // 1: server.admin.AdminAuthTokenResponse
	(*UpdatePasswordRequest)(nil),    // 2: server.admin.UpdatePasswordRequest
	(*UpdateEmailRequest)(nil),       // 3: server.admin.UpdateEmailRequest
	(*AdminRegisterRequest)(nil),     // 4: server.admin.AdminRegisterRequest
	(*AdminRegisterResponse)(nil),    // 5: server.admin.AdminRegisterResponse
	(*ResendInviteRequest)(nil),      // 6: server.admin.ResendInviteRequest
	(*emptypb.Empty)(nil),            // 7: google.protobuf.Empty
}
var file_v1_admin_Auth_proto_depIdxs = []int32{
	7, // 0: server.admin.AuthController.SignOut:input_type -> google.protobuf.Empty
	0, // 1: server.admin.AuthController.Refresh:input_type -> server.admin.AdminRefreshTokenRequest
	2, // 2: server.admin.AuthController.UpdatePassword:input_type -> server.admin.UpdatePasswordRequest
	3, // 3: server.admin.AuthController.UpdateEmail:input_type -> server.admin.UpdateEmailRequest
	4, // 4: server.admin.AuthController.Register:input_type -> server.admin.AdminRegisterRequest
	6, // 5: server.admin.AuthController.ResendInviteMail:input_type -> server.admin.ResendInviteRequest
	7, // 6: server.admin.AuthController.SignOut:output_type -> google.protobuf.Empty
	1, // 7: server.admin.AuthController.Refresh:output_type -> server.admin.AdminAuthTokenResponse
	7, // 8: server.admin.AuthController.UpdatePassword:output_type -> google.protobuf.Empty
	7, // 9: server.admin.AuthController.UpdateEmail:output_type -> google.protobuf.Empty
	5, // 10: server.admin.AuthController.Register:output_type -> server.admin.AdminRegisterResponse
	7, // 11: server.admin.AuthController.ResendInviteMail:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_admin_Auth_proto_init() }
func file_v1_admin_Auth_proto_init() {
	if File_v1_admin_Auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_Auth_proto_rawDesc), len(file_v1_admin_Auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_Auth_proto_goTypes,
		DependencyIndexes: file_v1_admin_Auth_proto_depIdxs,
		MessageInfos:      file_v1_admin_Auth_proto_msgTypes,
	}.Build()
	File_v1_admin_Auth_proto = out.File
	file_v1_admin_Auth_proto_goTypes = nil
	file_v1_admin_Auth_proto_depIdxs = nil
}
