// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/admin/Store.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // uuid.UUID
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BranchName      *string                `protobuf:"bytes,3,opt,name=BranchName,proto3,oneof" json:"BranchName,omitempty"`
	ZipCode         string                 `protobuf:"bytes,4,opt,name=ZipCode,proto3" json:"ZipCode,omitempty"`
	Address         string                 `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Tel             string                 `protobuf:"bytes,6,opt,name=Tel,proto3" json:"Tel,omitempty"`
	SiteURL         string                 `protobuf:"bytes,7,opt,name=SiteURL,proto3" json:"SiteURL,omitempty"`
	StampImageURL   string                 `protobuf:"bytes,8,opt,name=StampImageURL,proto3" json:"StampImageURL,omitempty"`
	Stayable        bool                   `protobuf:"varint,9,opt,name=Stayable,proto3" json:"Stayable,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	QRCode          string                 `protobuf:"bytes,11,opt,name=QRCode,proto3" json:"QRCode,omitempty"`                   // uuid.UUID
	UnLimitedQRCode string                 `protobuf:"bytes,12,opt,name=UnLimitedQRCode,proto3" json:"UnLimitedQRCode,omitempty"` // uuid.UUID
	StayableInfo    *StayableStoreInfo     `protobuf:"bytes,13,opt,name=StayableInfo,proto3,oneof" json:"StayableInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_v1_admin_Store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetBranchName() string {
	if x != nil && x.BranchName != nil {
		return *x.BranchName
	}
	return ""
}

func (x *Store) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Store) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Store) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Store) GetSiteURL() string {
	if x != nil {
		return x.SiteURL
	}
	return ""
}

func (x *Store) GetStampImageURL() string {
	if x != nil {
		return x.StampImageURL
	}
	return ""
}

func (x *Store) GetStayable() bool {
	if x != nil {
		return x.Stayable
	}
	return false
}

func (x *Store) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Store) GetQRCode() string {
	if x != nil {
		return x.QRCode
	}
	return ""
}

func (x *Store) GetUnLimitedQRCode() string {
	if x != nil {
		return x.UnLimitedQRCode
	}
	return ""
}

func (x *Store) GetStayableInfo() *StayableStoreInfo {
	if x != nil {
		return x.StayableInfo
	}
	return nil
}

type Stores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=Stores,proto3" json:"Stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stores) Reset() {
	*x = Stores{}
	mi := &file_v1_admin_Store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stores) ProtoMessage() {}

func (x *Stores) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stores.ProtoReflect.Descriptor instead.
func (*Stores) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{1}
}

func (x *Stores) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

type StoreRegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BranchName      *string                `protobuf:"bytes,2,opt,name=BranchName,proto3,oneof" json:"BranchName,omitempty"`
	ZipCode         string                 `protobuf:"bytes,3,opt,name=ZipCode,proto3" json:"ZipCode,omitempty"`
	Address         string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Tel             string                 `protobuf:"bytes,5,opt,name=Tel,proto3" json:"Tel,omitempty"`
	SiteURL         string                 `protobuf:"bytes,6,opt,name=SiteURL,proto3" json:"SiteURL,omitempty"`
	StampImageData  string                 `protobuf:"bytes,7,opt,name=StampImageData,proto3" json:"StampImageData,omitempty"`
	Stayable        bool                   `protobuf:"varint,8,opt,name=Stayable,proto3" json:"Stayable,omitempty"`
	IsActive        bool                   `protobuf:"varint,9,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	QRCode          string                 `protobuf:"bytes,10,opt,name=QRCode,proto3" json:"QRCode,omitempty"`
	UnLimitedQRCode string                 `protobuf:"bytes,11,opt,name=UnLimitedQRCode,proto3" json:"UnLimitedQRCode,omitempty"`
	StayableInfo    *StayableStoreInfo     `protobuf:"bytes,12,opt,name=StayableInfo,proto3,oneof" json:"StayableInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreRegisterRequest) Reset() {
	*x = StoreRegisterRequest{}
	mi := &file_v1_admin_Store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRegisterRequest) ProtoMessage() {}

func (x *StoreRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRegisterRequest.ProtoReflect.Descriptor instead.
func (*StoreRegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{2}
}

func (x *StoreRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreRegisterRequest) GetBranchName() string {
	if x != nil && x.BranchName != nil {
		return *x.BranchName
	}
	return ""
}

func (x *StoreRegisterRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *StoreRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StoreRegisterRequest) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *StoreRegisterRequest) GetSiteURL() string {
	if x != nil {
		return x.SiteURL
	}
	return ""
}

func (x *StoreRegisterRequest) GetStampImageData() string {
	if x != nil {
		return x.StampImageData
	}
	return ""
}

func (x *StoreRegisterRequest) GetStayable() bool {
	if x != nil {
		return x.Stayable
	}
	return false
}

func (x *StoreRegisterRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StoreRegisterRequest) GetQRCode() string {
	if x != nil {
		return x.QRCode
	}
	return ""
}

func (x *StoreRegisterRequest) GetUnLimitedQRCode() string {
	if x != nil {
		return x.UnLimitedQRCode
	}
	return ""
}

func (x *StoreRegisterRequest) GetStayableInfo() *StayableStoreInfo {
	if x != nil {
		return x.StayableInfo
	}
	return nil
}

type StoreUpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BranchName      *string                `protobuf:"bytes,3,opt,name=BranchName,proto3,oneof" json:"BranchName,omitempty"`
	ZipCode         string                 `protobuf:"bytes,4,opt,name=ZipCode,proto3" json:"ZipCode,omitempty"`
	Address         string                 `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Tel             string                 `protobuf:"bytes,6,opt,name=Tel,proto3" json:"Tel,omitempty"`
	SiteURL         string                 `protobuf:"bytes,7,opt,name=SiteURL,proto3" json:"SiteURL,omitempty"`
	StampImageData  string                 `protobuf:"bytes,8,opt,name=StampImageData,proto3" json:"StampImageData,omitempty"`
	Stayable        bool                   `protobuf:"varint,9,opt,name=Stayable,proto3" json:"Stayable,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	QRCode          string                 `protobuf:"bytes,11,opt,name=QRCode,proto3" json:"QRCode,omitempty"`
	UnLimitedQRCode string                 `protobuf:"bytes,12,opt,name=UnLimitedQRCode,proto3" json:"UnLimitedQRCode,omitempty"`
	StayableInfo    *StayableStoreInfo     `protobuf:"bytes,13,opt,name=StayableInfo,proto3" json:"StayableInfo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreUpdateRequest) Reset() {
	*x = StoreUpdateRequest{}
	mi := &file_v1_admin_Store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUpdateRequest) ProtoMessage() {}

func (x *StoreUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUpdateRequest.ProtoReflect.Descriptor instead.
func (*StoreUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{3}
}

func (x *StoreUpdateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *StoreUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreUpdateRequest) GetBranchName() string {
	if x != nil && x.BranchName != nil {
		return *x.BranchName
	}
	return ""
}

func (x *StoreUpdateRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *StoreUpdateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StoreUpdateRequest) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *StoreUpdateRequest) GetSiteURL() string {
	if x != nil {
		return x.SiteURL
	}
	return ""
}

func (x *StoreUpdateRequest) GetStampImageData() string {
	if x != nil {
		return x.StampImageData
	}
	return ""
}

func (x *StoreUpdateRequest) GetStayable() bool {
	if x != nil {
		return x.Stayable
	}
	return false
}

func (x *StoreUpdateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StoreUpdateRequest) GetQRCode() string {
	if x != nil {
		return x.QRCode
	}
	return ""
}

func (x *StoreUpdateRequest) GetUnLimitedQRCode() string {
	if x != nil {
		return x.UnLimitedQRCode
	}
	return ""
}

func (x *StoreUpdateRequest) GetStayableInfo() *StayableStoreInfo {
	if x != nil {
		return x.StayableInfo
	}
	return nil
}

type StayableStoreInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Parking               string                 `protobuf:"bytes,1,opt,name=Parking,proto3" json:"Parking,omitempty"`
	Latitude              float64                `protobuf:"fixed64,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude             float64                `protobuf:"fixed64,3,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	AccessInfo            string                 `protobuf:"bytes,4,opt,name=AccessInfo,proto3" json:"AccessInfo,omitempty"`
	RestAPIURL            string                 `protobuf:"bytes,5,opt,name=RestAPIURL,proto3" json:"RestAPIURL,omitempty"`
	BookingSystemID       string                 `protobuf:"bytes,6,opt,name=BookingSystemID,proto3" json:"BookingSystemID,omitempty"`
	BookingSystemLoginId  string                 `protobuf:"bytes,7,opt,name=BookingSystemLoginId,proto3" json:"BookingSystemLoginId,omitempty"`
	BookingSystemPassword string                 `protobuf:"bytes,8,opt,name=BookingSystemPassword,proto3" json:"BookingSystemPassword,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StayableStoreInfo) Reset() {
	*x = StayableStoreInfo{}
	mi := &file_v1_admin_Store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StayableStoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StayableStoreInfo) ProtoMessage() {}

func (x *StayableStoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StayableStoreInfo.ProtoReflect.Descriptor instead.
func (*StayableStoreInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{4}
}

func (x *StayableStoreInfo) GetParking() string {
	if x != nil {
		return x.Parking
	}
	return ""
}

func (x *StayableStoreInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *StayableStoreInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *StayableStoreInfo) GetAccessInfo() string {
	if x != nil {
		return x.AccessInfo
	}
	return ""
}

func (x *StayableStoreInfo) GetRestAPIURL() string {
	if x != nil {
		return x.RestAPIURL
	}
	return ""
}

func (x *StayableStoreInfo) GetBookingSystemID() string {
	if x != nil {
		return x.BookingSystemID
	}
	return ""
}

func (x *StayableStoreInfo) GetBookingSystemLoginId() string {
	if x != nil {
		return x.BookingSystemLoginId
	}
	return ""
}

func (x *StayableStoreInfo) GetBookingSystemPassword() string {
	if x != nil {
		return x.BookingSystemPassword
	}
	return ""
}

type StoreIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreIDRequest) Reset() {
	*x = StoreIDRequest{}
	mi := &file_v1_admin_Store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDRequest) ProtoMessage() {}

func (x *StoreIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDRequest.ProtoReflect.Descriptor instead.
func (*StoreIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{5}
}

func (x *StoreIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type QRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QRCode        string                 `protobuf:"bytes,1,opt,name=QRCode,proto3" json:"QRCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRResponse) Reset() {
	*x = QRResponse{}
	mi := &file_v1_admin_Store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRResponse) ProtoMessage() {}

func (x *QRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRResponse.ProtoReflect.Descriptor instead.
func (*QRResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{6}
}

func (x *QRResponse) GetQRCode() string {
	if x != nil {
		return x.QRCode
	}
	return ""
}

type UnlimitQRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlimitQRCode string                 `protobuf:"bytes,1,opt,name=UnlimitQRCode,proto3" json:"UnlimitQRCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlimitQRResponse) Reset() {
	*x = UnlimitQRResponse{}
	mi := &file_v1_admin_Store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlimitQRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlimitQRResponse) ProtoMessage() {}

func (x *UnlimitQRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_Store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlimitQRResponse.ProtoReflect.Descriptor instead.
func (*UnlimitQRResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_Store_proto_rawDescGZIP(), []int{7}
}

func (x *UnlimitQRResponse) GetUnlimitQRCode() string {
	if x != nil {
		return x.UnlimitQRCode
	}
	return ""
}

var File_v1_admin_Store_proto protoreflect.FileDescriptor

const file_v1_admin_Store_proto_rawDesc = "" +
	"\n" +
	"\x14v1/admin/Store.proto\x12\fserver.admin\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x03\n" +
	"\x05Store\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12#\n" +
	"\n" +
	"BranchName\x18\x03 \x01(\tH\x00R\n" +
	"BranchName\x88\x01\x01\x12\x18\n" +
	"\aZipCode\x18\x04 \x01(\tR\aZipCode\x12\x18\n" +
	"\aAddress\x18\x05 \x01(\tR\aAddress\x12\x10\n" +
	"\x03Tel\x18\x06 \x01(\tR\x03Tel\x12\x18\n" +
	"\aSiteURL\x18\a \x01(\tR\aSiteURL\x12$\n" +
	"\rStampImageURL\x18\b \x01(\tR\rStampImageURL\x12\x1a\n" +
	"\bStayable\x18\t \x01(\bR\bStayable\x12\x1a\n" +
	"\bIsActive\x18\n" +
	" \x01(\bR\bIsActive\x12\x16\n" +
	"\x06QRCode\x18\v \x01(\tR\x06QRCode\x12(\n" +
	"\x0fUnLimitedQRCode\x18\f \x01(\tR\x0fUnLimitedQRCode\x12H\n" +
	"\fStayableInfo\x18\r \x01(\v2\x1f.server.admin.StayableStoreInfoH\x01R\fStayableInfo\x88\x01\x01B\r\n" +
	"\v_BranchNameB\x0f\n" +
	"\r_StayableInfo\"5\n" +
	"\x06Stores\x12+\n" +
	"\x06Stores\x18\x01 \x03(\v2\x13.server.admin.StoreR\x06Stores\"\xbb\x03\n" +
	"\x14StoreRegisterRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12#\n" +
	"\n" +
	"BranchName\x18\x02 \x01(\tH\x00R\n" +
	"BranchName\x88\x01\x01\x12\x18\n" +
	"\aZipCode\x18\x03 \x01(\tR\aZipCode\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12\x10\n" +
	"\x03Tel\x18\x05 \x01(\tR\x03Tel\x12\x18\n" +
	"\aSiteURL\x18\x06 \x01(\tR\aSiteURL\x12&\n" +
	"\x0eStampImageData\x18\a \x01(\tR\x0eStampImageData\x12\x1a\n" +
	"\bStayable\x18\b \x01(\bR\bStayable\x12\x1a\n" +
	"\bIsActive\x18\t \x01(\bR\bIsActive\x12\x16\n" +
	"\x06QRCode\x18\n" +
	" \x01(\tR\x06QRCode\x12(\n" +
	"\x0fUnLimitedQRCode\x18\v \x01(\tR\x0fUnLimitedQRCode\x12H\n" +
	"\fStayableInfo\x18\f \x01(\v2\x1f.server.admin.StayableStoreInfoH\x01R\fStayableInfo\x88\x01\x01B\r\n" +
	"\v_BranchNameB\x0f\n" +
	"\r_StayableInfo\"\xb3\x03\n" +
	"\x12StoreUpdateRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12#\n" +
	"\n" +
	"BranchName\x18\x03 \x01(\tH\x00R\n" +
	"BranchName\x88\x01\x01\x12\x18\n" +
	"\aZipCode\x18\x04 \x01(\tR\aZipCode\x12\x18\n" +
	"\aAddress\x18\x05 \x01(\tR\aAddress\x12\x10\n" +
	"\x03Tel\x18\x06 \x01(\tR\x03Tel\x12\x18\n" +
	"\aSiteURL\x18\a \x01(\tR\aSiteURL\x12&\n" +
	"\x0eStampImageData\x18\b \x01(\tR\x0eStampImageData\x12\x1a\n" +
	"\bStayable\x18\t \x01(\bR\bStayable\x12\x1a\n" +
	"\bIsActive\x18\n" +
	" \x01(\bR\bIsActive\x12\x16\n" +
	"\x06QRCode\x18\v \x01(\tR\x06QRCode\x12(\n" +
	"\x0fUnLimitedQRCode\x18\f \x01(\tR\x0fUnLimitedQRCode\x12C\n" +
	"\fStayableInfo\x18\r \x01(\v2\x1f.server.admin.StayableStoreInfoR\fStayableInfoB\r\n" +
	"\v_BranchName\"\xbb\x02\n" +
	"\x11StayableStoreInfo\x12\x18\n" +
	"\aParking\x18\x01 \x01(\tR\aParking\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x03 \x01(\x01R\tLongitude\x12\x1e\n" +
	"\n" +
	"AccessInfo\x18\x04 \x01(\tR\n" +
	"AccessInfo\x12\x1e\n" +
	"\n" +
	"RestAPIURL\x18\x05 \x01(\tR\n" +
	"RestAPIURL\x12(\n" +
	"\x0fBookingSystemID\x18\x06 \x01(\tR\x0fBookingSystemID\x122\n" +
	"\x14BookingSystemLoginId\x18\a \x01(\tR\x14BookingSystemLoginId\x124\n" +
	"\x15BookingSystemPassword\x18\b \x01(\tR\x15BookingSystemPassword\" \n" +
	"\x0eStoreIDRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"$\n" +
	"\n" +
	"QRResponse\x12\x16\n" +
	"\x06QRCode\x18\x01 \x01(\tR\x06QRCode\"9\n" +
	"\x11UnlimitQRResponse\x12$\n" +
	"\rUnlimitQRCode\x18\x01 \x01(\tR\rUnlimitQRCode2\xf5\x03\n" +
	"\x0fStoreController\x12>\n" +
	"\aGetByID\x12\x1c.server.admin.StoreIDRequest\x1a\x13.server.admin.Store\"\x00\x128\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x14.server.admin.Stores\"\x00\x12>\n" +
	"\fGetActiveAll\x12\x16.google.protobuf.Empty\x1a\x14.server.admin.Stores\"\x00\x12E\n" +
	"\bRegister\x12\".server.admin.StoreRegisterRequest\x1a\x13.server.admin.Store\"\x00\x12A\n" +
	"\x06Update\x12 .server.admin.StoreUpdateRequest\x1a\x13.server.admin.Store\"\x00\x12G\n" +
	"\vRegenQRCode\x12\x1c.server.admin.StoreIDRequest\x1a\x18.server.admin.QRResponse\"\x00\x12U\n" +
	"\x12RegenUnlimitQRCode\x12\x1c.server.admin.StoreIDRequest\x1a\x1f.server.admin.UnlimitQRResponse\"\x00B\x84\x01\n" +
	"\x10com.server.adminB\n" +
	"StoreProtoP\x01Z\x13server/api/v1/admin\xa2\x02\x03SAX\xaa\x02\fServer.Admin\xca\x02\fServer\\Admin\xe2\x02\x18Server\\Admin\\GPBMetadata\xea\x02\rServer::Adminb\x06proto3"

var (
	file_v1_admin_Store_proto_rawDescOnce sync.Once
	file_v1_admin_Store_proto_rawDescData []byte
)

func file_v1_admin_Store_proto_rawDescGZIP() []byte {
	file_v1_admin_Store_proto_rawDescOnce.Do(func() {
		file_v1_admin_Store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_Store_proto_rawDesc), len(file_v1_admin_Store_proto_rawDesc)))
	})
	return file_v1_admin_Store_proto_rawDescData
}

var file_v1_admin_Store_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_admin_Store_proto_goTypes = []any{
	(*Store)(nil),                // 0: server.admin.Store
	(*Stores)(nil),               // 1: server.admin.Stores
	(*StoreRegisterRequest)(nil), // 2: server.admin.StoreRegisterRequest
	(*StoreUpdateRequest)(nil),   // 3: server.admin.StoreUpdateRequest
	(*StayableStoreInfo)(nil),    // 4: server.admin.StayableStoreInfo
	(*StoreIDRequest)(nil),       // 5: server.admin.StoreIDRequest
	(*QRResponse)(nil),           // 6: server.admin.QRResponse
	(*UnlimitQRResponse)(nil),    // 7: server.admin.UnlimitQRResponse
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_v1_admin_Store_proto_depIdxs = []int32{
	4,  // 0: server.admin.Store.StayableInfo:type_name -> server.admin.StayableStoreInfo
	0,  // 1: server.admin.Stores.Stores:type_name -> server.admin.Store
	4,  // 2: server.admin.StoreRegisterRequest.StayableInfo:type_name -> server.admin.StayableStoreInfo
	4,  // 3: server.admin.StoreUpdateRequest.StayableInfo:type_name -> server.admin.StayableStoreInfo
	5,  // 4: server.admin.StoreController.GetByID:input_type -> server.admin.StoreIDRequest
	8,  // 5: server.admin.StoreController.GetAll:input_type -> google.protobuf.Empty
	8,  // 6: server.admin.StoreController.GetActiveAll:input_type -> google.protobuf.Empty
	2,  // 7: server.admin.StoreController.Register:input_type -> server.admin.StoreRegisterRequest
	3,  // 8: server.admin.StoreController.Update:input_type -> server.admin.StoreUpdateRequest
	5,  // 9: server.admin.StoreController.RegenQRCode:input_type -> server.admin.StoreIDRequest
	5,  // 10: server.admin.StoreController.RegenUnlimitQRCode:input_type -> server.admin.StoreIDRequest
	0,  // 11: server.admin.StoreController.GetByID:output_type -> server.admin.Store
	1,  // 12: server.admin.StoreController.GetAll:output_type -> server.admin.Stores
	1,  // 13: server.admin.StoreController.GetActiveAll:output_type -> server.admin.Stores
	0,  // 14: server.admin.StoreController.Register:output_type -> server.admin.Store
	0,  // 15: server.admin.StoreController.Update:output_type -> server.admin.Store
	6,  // 16: server.admin.StoreController.RegenQRCode:output_type -> server.admin.QRResponse
	7,  // 17: server.admin.StoreController.RegenUnlimitQRCode:output_type -> server.admin.UnlimitQRResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_admin_Store_proto_init() }
func file_v1_admin_Store_proto_init() {
	if File_v1_admin_Store_proto != nil {
		return
	}
	file_v1_admin_Store_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_admin_Store_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_admin_Store_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_Store_proto_rawDesc), len(file_v1_admin_Store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_Store_proto_goTypes,
		DependencyIndexes: file_v1_admin_Store_proto_depIdxs,
		MessageInfos:      file_v1_admin_Store_proto_msgTypes,
	}.Build()
	File_v1_admin_Store_proto = out.File
	file_v1_admin_Store_proto_goTypes = nil
	file_v1_admin_Store_proto_depIdxs = nil
}
